### PR TITLE
Rename solvers to be consistent with others

### PR DESCRIPTION
**Pull request by sparsh2**
Hi @cs0x7f,

I have renamed 3 solvers - `Cross`, `EOLine`, `Roux S1` solvers from "solve cross", "solve EOLine", "solve Roux S1" to "Cross", "EOLine", "Roux S1" to be consistent with the other solver names in `Tools` -> `Function: Solvers`

image

Let me know if I am missing any steps to get these changes in.

Thanks

### CODE REVIEW

**Comment by afedotov** [comment]
Hey!
i18n files are managed externally via Crowdin, so no any PR is accepted with direct changes to i18n files. Just withdraw this PR and submit this changes via Crowdin.

**Comment by sparsh2** [comment]
@afedotov Thanks! I am assuming this - https://crowdin.com/project/cstimer ? I am new to Crowdin, are there any guidelines I can follow to get those changes in?

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/5540604500cdf6ab109c86d070c3da2ba1e89ad0

**Comment by sparsh2** [comment]
Thanks! @afedotov @cs0x7f

**Pull request closed without merging**
