### PR TITLE
Add checkbox for confirming deletion

### PR DESCRIPTION
**Pull request by NorbertCode**
Vivaldi web-apps don't support Javascript pop-up windows. Since csTimer uses them to confirm deletion, it's impossible to delete a time.

A way to solve this problem would be adding a checkbox, which controls whether this pop-up should be shown.

The way I've done it only works when Multiple Deletion is disabled, because Multiple Deletion requires a pop-up to enter how many rows to delete. I'm not sure if this is more intuitive than Confirm Deletion overriding it, so I'm open to suggestions.

From testing on my local machine it looks like everything works, but I'm not sure if it would on a production server.

Also, I couldn't find any contribution guidelines so I only modified options for the English language, so the setting doesn't exist in other ones.

### CODE REVIEW

**Comment by cs0x7f** [comment]
The problem you raise does need to be addressed, but I don't think adding an option is the right way to do it.
What does it look like in your browser for the case where confirm is not available?
Does windows.confirm is undefined, or does it always return "Cancel"?

**Comment by NorbertCode** [comment]
The pop-up isn't displayed at all. The confirm() function returns false and, when Multiple Deletion is enabled, prompt() sets n_del to null.

**Comment by cs0x7f** [comment]
I have made a simple implementation here ( https://github.com/cs0x7f/cstimer/commit/d4c08f84d3cf63f960cb58caba562ee01df4626e ). When it is detected that the pop-up dialog is blocked (the duration is less than 20ms), a prompt will be displayed through the logo, and default behavior will be directly adopted when the second click occurs.

**Comment by NorbertCode** [comment]
Your implementation completely fixes the problem I was having in a much more intuitive way than what I proposed.

Thanks for taking the time to review and fix this somewhat obscure issue.

**Pull request closed without merging**
