### PR TITLE
Support for GAN Smart Timer using its Bluetooth protocol

### PR DESCRIPTION
**Pull request by afedotov**
Hi! Good to see you back and doing commits, I hope everything is fine with you!

This PR adds support for GAN Smart Timer via its bluetooth protocol.

Also I've added shell scripts to build and run project locally using Docker containers.
This will make local development easer for those who want contribute to project.

### CODE REVIEW

**Comment by cs0x7f** [comment]
Would you mind providing some more details about the protocol of gan timer?
Is it obtained by an official document of gan, or obtained by reverse engineering?

**Comment by cs0x7f** [comment]
Would you mind providing some more details about the protocol of gan timer?
Is it obtained by an official document of gan, or obtained by reverse engineering?

**Comment by afedotov** [comment]
> Would you mind providing some more details about the protocol of gan timer? Is it obtained by an official document of gan, or obtained by reverse engineering?

I would not call it full-fledged reverse engineering, but something like that.

I heard from Cubeast author on his Discord server that GAN nowadays is changing their policy and welcome developers to support their timers. They send him sample timers with protocol specification. But sending him specs was for nothing really because he long time ago has it by reverse engineering :)

**Comment by cs0x7f** [comment]
Already merged gantimer.js into main branch. Since I don't have a gan timer, I'll ask some of my friends to test it. If all goes well, it will be deployed to beta version ( /new/ ) in 1 or 2 weeks.

**Comment by afedotov** [comment]
> Already merged gantimer.js into main branch. Since I don't have a gan timer, I'll ask some of my friends to test it. If all goes well, it will be deployed to beta version ( /new/ ) in 1 or 2 weeks.

That's great!
BTW I didn't understand why you doesn't include any of translation files. Without updating list of timers in `PROPERTY_ENTERING_STR` it won't be shown in selection menu, at least it will be shown as empty string.

And about this change in `kernel.js`:
https://github.com/cs0x7f/cstimer/commit/a842f6330ee12393b846a013a1809dff95aec897#diff-e97c4824c430ec90072e637dd4e208a56337024006ccf4971a00d114c6c14504

It is not related to GAN timer support, but fixes issue with replacing `-<br>` line breaks for `BUTTON_EXPORT` button label used in some translations, `ru-ru.js` for example. Maybe this should be included by separate commit.

**Comment by cs0x7f** [comment]
The translation files are managed by crowdin. Merge them directly might cause some other issues that might be more serious, while keeping the selection item empty does not affect internal testing.

The "-<br>" is fixed by replacing string to regex /-?<br>-?/g in https://github.com/cs0x7f/cstimer/commit/b7ee89229d5a0be3a4dfb90dc92d7d48354b5ad7

**Comment by afedotov** [comment]
Ah, I see, thanks!

**Pull request merged**
