### PR TITLE
Reconstruction tool imporvements

### PR DESCRIPTION
**Pull request by afedotov**
Sorry if it is so bulk for one PR, but most fixes are related. Anyway I can split them if required.
There are multiple improvements in this PR, description by each commit:

1. Actual bluetooth cube solving progress phase should be detected before first cube turn. Unless if you, for example, scramble cube with arbitrary PLL, then mark scramble and solve it, first move will be placed to first phase (cross for example), not to PLL. Also there is disambiguation across different places in csTimer what cube "moves" and "turns" exactly are. So print on multi-phase lcd STM (Slice Turn Metric) and RQTM (Raw Quarter Turn Metric) instead of "Moves".

2. Reconstruction tool incorrectly calculates number of turns. The problem is in the wrongly specified сongruence relation modulo 3 which is used to determine if both faces are on the same axis (U and D, F and B, L and R). This causes funny behavior when `UUUU` counts as 1 move but `LLLL` as 4 moves. Also instead of showing "turn" it is better to clearly specify what these numbers exactly are - HTM (Half Turn Metric).

   > BTW, there is some inconsistency exists with moves calculation. User can observe different
   > HTM numbers in reconstruction tool than in alg.cubing.net. This can be fixed, if
   > `cubeutil.getPrettyMoves` can reorder same axis moves during simplification. For example 
   > `R L R L` raw sequence will be calculated as 2 HTM in Reconstruction tool and as 4 HTM 
   > when passing reconstruction to alg.cubing.net. But if simplification will reorder 
   > `R L R L -> RRLL -> R2L2` it will be counted as 2 HTM. So far I don't know how to fix
   > `getPrettyMoves`.

3. Added `Open Review` link to the Reconstruction Tool. Same like the Last Solve link in the Bluetooth Cube tool. But now any past solve can be reconstructed, pretty formatted and opened in the alg.cubing.net.

4. Added simple instructions about bluetooth connectivity to the all bluetooth connection dialogs. Also changed dialog name from "Giiker Cube" to "Bluetooth Cube" as there are not only Giiker cubes supported.

Screenshots:
Screen Shot 2023-03-29 at 01 20 28
Screen Shot 2023-03-29 at 01 20 43
Screen Shot 2023-03-29 at 01 21 12

### CODE REVIEW

**Comment by cs0x7f** [comment]
Awesome work!
There are some details that I will tweak to. Mainly the i18n you also mentioned, and the return value of calcRecons. It already returns an array of each step, and rawMoves can be thrown directly into the array (I remember doing this before, but later deleted it)

**Comment by afedotov** [comment]
> Awesome work! There are some details that I will tweak to. Mainly the i18n you also mentioned, and the return value of calcRecons. It already returns an array of each step, and rawMoves can be thrown directly into the array (I remember doing this before, but later deleted it)

Yes, I've remember about that i18n managed externally, so made it possible to easily move that constant to i18n files later. I don't know how much of priority, anyway there are more places like this exists w/o i18n so far.

About `calcRecons`
`rawMoves` itself as is can't be placed to recons row data, because it can't be a data row, and can't be a data column. Instead `rawMoves` should be decomposed and each separate stage from rawMoves placed as column in row data. But such data structure will not be compatible with `rawMoves` and corresponding functions used in `timer.js`. I just want to make them the same, non-repetitive and compatible. Anyway you can change this PR as it suits you best, or I can refactor, as you like.

**Comment by cs0x7f** [comment]
It seems that there are some other problems that cause the reconstruction (in recons tools) to be wrong. Note that this function is not only valid for Bluetooth Cube, it is also valid for solutions from virtual cube. However, in a solution generated by virtual cube, there can be cube rotations (x, y, z), but it seems to be lost in the current processing because `effMove` is null for cube rotations. Of course this shouldn't be a big problem, I'll be able to fix them later.

**Comment by afedotov** [comment]
> However, in a solution generated by virtual cube, there can be cube rotations (x, y, z), but it seems to be lost in the current processing because `effMove` is null for cube rotations. Of course this shouldn't be a big problem, I'll be able to fix them later.

Isn't it ok to process but not count `x,y,z` moves since it is HTM, not ETM metric?

**Comment by cs0x7f** [comment]
The counting is not the main problem. The problem is that cubeutil.getPrettyMoves cannot handle these rotations at present, so the generated reconstruction for alg.cubing.net must be wrong.

**Comment by cs0x7f** [comment]
I mean, the link to alg.cubing.net is partly wrong, the cube won't be solved properly. The recons tools themselves are fine, this part of the code is not affected by the new update.

**Comment by cs0x7f** [comment]
For counting, since the virtual cube can directly do MES moves, it is neither HTM nor STM.

**Pull request merged**
